export const SPEC_INFLATION_CONFIG = {
  advancedAITerms: [
    "agentic",
    "autonomous agents",
    "semantic search",
    "rag",
    "retrieval-augmented",
    "embeddings",
    "vector db",
    "vector database",
    "ci/cd automation",
    "mlops",
    "llmops",
    "copilots",
    "fine-tuning",
    "fine tuning",
    "prompt engineering",
    "langchain",
    "llamaindex",
    "multi-agent",
    "multi agent",
    "knowledge graph",
    "neural search",
  ],

  businessOutcomeTerms: [
    "revenue",
    "margin",
    "cost",
    "roi",
    "p&l",
    "growth",
    "retention",
    "fraud",
    "risk",
    "conversion",
    "operational efficiency",
    "profit",
    "earnings",
    "customer lifetime value",
    "churn",
    "market share",
    "pipeline",
    "bookings",
    "arpu",
    "unit economics",
  ],

  thresholds: {
    advancedDensity: { low: 2, med: 4, high: 6 },
    businessDensity: { low: 2, med: 4, high: 6 },
  },

  penalties: {
    highAdvLowBiz: -10,
    highAdvMedBiz: -5,
    medAdvLowBiz: -5,
    medAdvMedBiz: -2,
  },

  maxPenalty: -10,
};
